app/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from app.controllers import register_user, get_shop_data
from app.models import User, Product, ProductDetailImages, Favorite, Review, Contact, db
from app.forms import LoginForm, RegisterForm, ContactForm
from werkzeug.security import generate_password_hash, check_password_hash
from flask import jsonify
from sqlalchemy import or_

# Create a blueprint
routes_bp = Blueprint('routes_bp', __name__)



@routes_bp.route('/')
@routes_bp.route('/home', endpoint='home')
def shop():
    # Use the shop function to get data
    context = get_shop_data()
    return render_template('shop.html', **context)




@routes_bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()  # Instantiate the form
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data

        # Debugging: Print email and password to check if they are correctly captured
        print(f"Login attempt with email: {email} and password: {password}")

        # Check if the user exists and the password is correct
        user = User.query.filter_by(email=email).first()

        if user and check_password_hash(user.password, password):
            # Log the user in by storing info in session
            session['user_id'] = user.id
            session['username'] = user.name
            print(f"User {user.name} logged in successfully.")  # Debugging message
            flash('Logged in successfully!', 'success')
            return redirect(url_for('routes_bp.shop'))  # Redirect to the shop page after login
        else:
            print("Invalid login attempt.")  # Debugging message
            flash('Invalid email or password', 'danger')

    print("Form validation failed.")  # Debugging message
    return render_template('login.html', form=form)

@routes_bp.route('/logout')
def logout():
    # Clear the session to log out the user
    session.clear()
    flash('You have been logged out.', 'success')
    return redirect(url_for('routes_bp.shop'))

@routes_bp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()

    if form.validate_on_submit():
        # Check if the email is already registered
        if User.query.filter_by(email=form.email.data).first():
            flash('Email address already registered.', 'danger')
            return redirect(url_for('routes_bp.register'))

        # Get data from form fields
        name = form.name.data
        email = form.email.data
        password = form.password.data

        # Hash the password for security
        hashed_password = generate_password_hash(password, method='pbkdf2:sha256')

        # Create a new user instance
        new_user = User(name=name, email=email, password=hashed_password)

        try:
            db.session.add(new_user)
            db.session.commit()
            print("User added to the database successfully")  # Debug message
            flash('Registration successful! You can now log in.', 'success')
            return redirect(url_for('routes_bp.login'))  # Redirect to the login page after registration
        except Exception as e:
            db.session.rollback()
            print(f"Error while adding user to the database: {e}")  # Print the actual error message
            flash('An error occurred while registering. Please try again.', 'danger')

    else:
        # If form validation fails, print errors
        print(form.errors)  # This will print validation errors to the console if there are any

    return render_template('register.html', form=form)


@routes_bp.route('/search')
def search():
    query = request.args.get('query')

    # If the search query is empty, redirect to the shop page
    if not query:
        flash('Please enter a search term.', 'warning')
        return redirect(url_for('routes_bp.shop'))

    # Search products by name or description
    search_results = Product.query.filter(
        or_(
            Product.name.ilike(f'%{query}%'),
            Product.description.ilike(f'%{query}%')
        )
    ).all()

    if not search_results:
        flash('No products found matching your search.', 'warning')

    # Reuse the shop.html template to display the search results
    return render_template('shop.html', products=search_results, search_query=query)



@routes_bp.route('/add_to_favorite/<int:product_id>', methods=['POST'])
def add_to_favorite(product_id):
    user_id = session.get('user_id')  # Assuming the user is logged in and their ID is stored in the session

    if not user_id:
        flash('You need to log in to add products to your favorites.', 'danger')
        return redirect(url_for('routes_bp.login'))

    # Check if the product exists
    product = Product.query.get_or_404(product_id)

    # Check if the product is already in the user's favorites
    existing_favorite = Favorite.query.filter_by(user_id=user_id, product_id=product_id).first()
    if existing_favorite:
        flash(f'{product.name} is already in your favorites.', 'warning')
    else:
        # Add product to the user's favorites
        favorite = Favorite(user_id=user_id, product_id=product.id)

        try:
            db.session.add(favorite)
            db.session.commit()
            flash(f'{product.name} has been added to your favorites.', 'success')
        except Exception as e:
            db.session.rollback()
            flash('An error occurred while adding the product to your favorites.', 'danger')
            print(f"Error: {e}")

    # Redirect back to the product detail page
    return redirect(url_for('routes_bp.detail', product_id=product.id))




@routes_bp.route('/product/<int:product_id>')
def detail(product_id):
    # Fetch the product from the database by ID
    product = Product.query.get_or_404(product_id)

    # Query all images associated with this product
    product_images = ProductDetailImages.query.filter_by(product_id=product_id).all()

    # Fetch reviews for this product
    reviews = Review.query.filter_by(product_id=product_id, active='1').all()
    review_count = len(reviews)

    # Fetch related products from the same category, excluding the current product
    related_products = Product.query.filter(
        Product.category_id == product.category_id,  # Same category
        Product.id != product_id  # Exclude the current product
    ).limit(8).all()

    # Pass the product to the template
    return render_template('detail.html', 
                           product=product, 
                           product_images=product_images, 
                           reviews=reviews, 
                           review_count=review_count, 
                           related_products=related_products)



@routes_bp.route('/favorite')
def favorite():
    user_id = session.get('user_id')  # Assuming you store user_id in session
    if not user_id:
        # Redirect to login if user is not authenticated
        return redirect(url_for('routes_bp.login'))

    # Get favorite products for the user
    favorite_products = Favorite.query.filter_by(user_id=user_id).all()

    # You can also join the Product table to get more details about the product
    favorite_products_with_details = [
        { 
            'id': fav.product.id,  # Include the product ID here
            'name': fav.product.name,
            'price': fav.product.price,
            'image': fav.product.img_path
        }
        for fav in favorite_products
    ]

    return render_template('favorites.html', favorite_products=favorite_products_with_details)

@routes_bp.route('/remove_favorite/<int:product_id>', methods=['POST'])
def remove_favorite(product_id):
    user_id = session.get('user_id')
    if not user_id:
        return redirect(url_for('routes_bp.login'))

    # Find the favorite entry and remove it
    favorite = Favorite.query.filter_by(user_id=user_id, product_id=product_id).first()
    if favorite:
        db.session.delete(favorite)
        db.session.commit()

    return redirect(url_for('routes_bp.favorite'))

@routes_bp.route('/add_review/<int:product_id>', methods=['POST'])
def add_review(product_id):
    user_id = session.get('user_id')
    if not user_id:
        return jsonify({'error': 'You need to log in.'}), 401  # Returning JSON for AJAX error

    review_text = request.form.get('review')
    if not review_text:
        return jsonify({'error': 'Review cannot be empty.'}), 400  # Returning JSON for AJAX error

    new_review = Review(user_id=user_id, product_id=product_id, review=review_text)
    try:
        db.session.add(new_review)
        db.session.commit()

        # Fetch updated reviews to send back in the AJAX response
        reviews = Review.query.filter_by(product_id=product_id).all()
        review_count = len(reviews)

        # Render the reviews_section partial and send it back to the client
        reviews_html = render_template('partials/reviews_section.html', reviews=reviews, review_count=review_count)
        
        return jsonify({'reviews_html': reviews_html, 'review_count': review_count}), 200
    except Exception as e:
        db.session.rollback()
        return jsonify({'error': 'An error occurred while submitting your review.'}), 500


@routes_bp.route('/contact', methods=['GET', 'POST'])
def contact():
    form = ContactForm()

    if form.validate_on_submit():
        # Process the form data
        new_contact = Contact(
            name=form.name.data,
            email=form.email.data,
            subject=form.subject.data,
            message=form.message.data
        )

        try:
            db.session.add(new_contact)
            db.session.commit()
            flash('Your message has been sent successfully!', 'success')
            return redirect(url_for('routes_bp.contact'))  # Redirect after form submission
        except Exception as e:
            db.session.rollback()

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>{% block title %}EShopper{% endblock %}</title>
      
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta content="Free HTML Templates" name="keywords" />
    <meta content="Free HTML Templates" name="description" />

    <!-- Favicon --> 
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
<img src="{{ url_for('static', filename='img/favicon.ico') }}" alt="favicon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet" />

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet" />

  </head>

  <body>

    <!-- Topbar Start -->
    <div class="container-fluid">
      <div class="row bg-secondary py-2 px-xl-5">
        <div class="col-lg-6 d-none d-lg-block">
          <div class="d-inline-flex align-items-center">
            <a class="text-dark" href="">FAQs</a>
            <span class="text-muted px-2">|</span>
            <a class="text-dark" href="">Help</a>
            <span class="text-muted px-2">|</span>
            <a class="text-dark" href="">Support</a>
          </div>
        </div>
        <div class="col-lg-6 text-center text-lg-right">
          <div class="d-inline-flex align-items-center">
            <a class="text-dark px-2" href="">
              <i class="fab fa-facebook-f"></i>
            </a>
            <a class="text-dark px-2" href="">
              <i class="fab fa-twitter"></i>
            </a>
            <a class="text-dark px-2" href="">
              <i class="fab fa-linkedin-in"></i>
            </a>
            <a class="text-dark px-2" href="">
              <i class="fab fa-instagram"></i>
            </a>
            <a class="text-dark pl-2" href="">
              <i class="fab fa-youtube"></i>
            </a>
          </div>
        </div>
      </div>
      <div class="row align-items-center py-3 px-xl-5">
        <div class="col-lg-3 d-none d-lg-block">
          <a href="" class="text-decoration-none">
            <h1 class="m-0 display-5 font-weight-semi-bold">
              <span class="text-primary font-weight-bold border px-3 mr-1">E</span>Shopper
            </h1>
          </a>
        </div>



        <div class="col-lg-6 col-6 text-left">
          <form action="{{ url_for('routes_bp.search') }}" method="GET">
              <div class="input-group">
                  <input type="text" name="query" class="form-control" placeholder="Search for products" />
                  <div class="input-group-append">
                      <button type="submit" class="btn bg-transparent text-primary">
                          <i class="fa fa-search"></i>
                      </button>
                  </div>
              </div>
          </form>
      </div>


        <div class="col-lg-3 col-6 text-right">
         
            <a href="{{ url_for('routes_bp.favorite') }}" class="btn border">
              <i class="fas fa-heart text-primary"></i>
              <span class="badge">{{ favorites_count }}</span>
          </a>
         

          <a href="" class="btn border">
            <i class="fas fa-shopping-cart text-primary"></i>
            <span class="badge">0</span>
          </a>
        </div>
      </div>
    </div>
    <!-- Topbar End -->

    <!-- Navbar Start -->
    <div class="container-fluid">
      <div class="row border-top px-xl-5">
        <div class="col-lg-3 d-none d-lg-block">
          <a class="btn shadow-none d-flex align-items-center justify-content-between bg-primary text-white w-100" data-toggle="collapse" href="#navbar-vertical" style="height: 65px; margin-top: -1px; padding: 0 30px">
            <h6 class="m-0">Categories</h6>
            <i class="fa fa-angle-down text-dark"></i>
          </a>
          <nav class="collapse position-absolute navbar navbar-vertical navbar-light align-items-start p-0 border border-top-0 border-bottom-0 bg-light" id="navbar-vertical" style="width: calc(100% - 30px); z-index: 1">
            <div class="navbar-nav w-100 overflow-hidden" style="height: 410px">

            {% block categories %}
            {% for category in categories_with_count %}
                <a href="{{ url_for('routes_bp.shop', category=category.id) }}" class="nav-item nav-link">
                    {{ category.name }} ({{ category.product_count }})
                </a>
            {% endfor %}
        {% endblock %}
        
   
            </div>

          </nav>
        </div>
        <div class="col-lg-9">
          <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0">
            <a href="" class="text-decoration-none d-block d-lg-none">
              <h1 class="m-0 display-5 font-weight-semi-bold">
                <span class="text-primary font-weight-bold border px-3 mr-1">E</span>Shopper
              </h1>
            </a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
              <div class="navbar-nav mr-auto py-0">
                <a href="{{ url_for('routes_bp.home') }}" class="nav-item nav-link">Shop</a>


        <a href="{{ url_for('routes_bp.detail', product_id=1) }}" class="nav-item nav-link">Shop Detail</a>

                <a href="{{ url_for('routes_bp.contact') }}" class="nav-item nav-link active">Contact</a>
                
              </div>

              {% if session.get('username') %}
              <a href="{{ url_for('routes_bp.logout') }}" class="nav-item nav-link">Logout</a>
              {% else %}
              <a href="{{ url_for('routes_bp.login') }}" class="nav-item nav-link">Login</a>
              <a href="{{ url_for('routes_bp.register') }}" class="nav-item nav-link">Register</a>
              {% endif %}          

            </div>
          </nav>
        </div>
      </div>
    </div>
    <!-- Navbar End -->

    <!-- Page Header Start -->
    <div class="container-fluid bg-secondary mb-5">
      <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 300px">
        <h1 class="font-weight-semi-bold text-uppercase mb-3">{% block page_title %}Our Shop{% endblock %}</h1>
        <div class="d-inline-flex">
          <p class="m-0"><a href="{{ url_for('routes_bp.home') }}">Home</a></p>
          <p class="m-0 px-2">-</p>
          <p class="m-0">{% block breadcrumb %}Shop{% endblock %}</p>
        </div>
      </div>
    </div>
    <!-- Page Header End -->

    {% block content %}
    
    {% endblock %}
    
    <!-- Footer Start -->
    <div class="container-fluid bg-secondary text-dark mt-5 pt-5">
      <div class="row px-xl-5 pt-5">
        <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
          <a href="" class="text-decoration-none">
            <h1 class="mb-4 display-5 font-weight-semi-bold">
              <span
                class="text-primary font-weight-bold border border-white px-3 mr-1"
                >E</span
              >Shopper
            </h1>
          </a>
          <p>
            Dolore erat dolor sit lorem vero amet. Sed sit lorem magna, ipsum no
            sit erat lorem et magna ipsum dolore amet erat.
          </p>
          <p class="mb-2">
            <i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street,
            New York, USA
          </p>
          <p class="mb-2">
            <i class="fa fa-envelope text-primary mr-3"></i>info@example.com
          </p>
          <p class="mb-0">
            <i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890
          </p>
        </div>
        <div class="col-lg-8 col-md-12">
          <div class="row">
            <div class="col-md-4 mb-5">
              <h5 class="font-weight-bold text-dark mb-4">Quick Links</h5>
              <div class="d-flex flex-column justify-content-start">
                <a class="text-dark mb-2" href="index.html"
                  ><i class="fa fa-angle-right mr-2"></i>Home</a
                >
                <a class="text-dark mb-2" href="shop.html"
                  ><i class="fa fa-angle-right mr-2"></i>Our Shop</a
                >

                {% for product in products %}
                <a href="{{ url_for('routes_bp.detail', product_id=product.id) }}" class="text-dark mb-2">Shop Detail</a>
                {% endfor %}


                <a class="text-dark mb-2" href="cart.html"
                  ><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a
                >
                <a class="text-dark mb-2" href="checkout.html"
                  ><i class="fa fa-angle-right mr-2"></i>Checkout</a
                >
                <a class="text-dark" href="contact.html"
                  ><i class="fa fa-angle-right mr-2"></i>Contact Us</a
                >
              </div>
            </div>
            <div class="col-md-4 mb-5">
              <h5 class="font-weight-bold text-dark mb-4">Quick Links</h5>
              <div class="d-flex flex-column justify-content-start">
                <a class="text-dark mb-2" href="index.html"
                  ><i class="fa fa-angle-right mr-2"></i>Home</a
                >
                <a class="text-dark mb-2" href="shop.html"
                  ><i class="fa fa-angle-right mr-2"></i>Our Shop</a
                >

                {% for product in products %}
                <a href="{{ url_for('routes_bp.detail', product_id=product.id) }}" class="text-dark mb-2">Shop Detail</a>
                {% endfor %}

                <a class="text-dark mb-2" href="cart.html"
                  ><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a
                >
                <a class="text-dark mb-2" href="checkout.html"
                  ><i class="fa fa-angle-right mr-2"></i>Checkout</a
                >
                <a class="text-dark" href="contact.html"
                  ><i class="fa fa-angle-right mr-2"></i>Contact Us</a
                >
              </div>
            </div>
            <div class="col-md-4 mb-5">
              <h5 class="font-weight-bold text-dark mb-4">Newsletter</h5>
              <form action="">
                <div class="form-group">
                  <input
                    type="text"
                    class="form-control border-0 py-4"
                    placeholder="Your Name"
                    required="required"
                  />
                </div>
                <div class="form-group">
                  <input
                    type="email"
                    class="form-control border-0 py-4"
                    placeholder="Your Email"
                    required="required"
                  />
                </div>
                <div>
                  <button
                    class="btn btn-primary btn-block border-0 py-3"
                    type="submit"
                  >
                    Subscribe Now
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
      <div class="row border-top border-light mx-xl-5 py-4">
        <div class="col-md-6 px-xl-0">
          <p class="mb-md-0 text-center text-md-left text-dark">
            &copy;
            <a class="text-dark font-weight-semi-bold" href="#"
              >Your Site Name</a
            >. All Rights Reserved. Designed by
            <a
              class="text-dark font-weight-semi-bold"
              href="https://htmlcodex.com"
              >HTML Codex</a
            >
          </p>
        </div>
        <div class="col-md-6 px-xl-0 text-center text-md-right">
          <img class="img-fluid w-100" src="{{ url_for('static', filename='img/payments.png') }}" alt="" />
        </div>
      </div>
    </div>
    <!-- Footer End -->

    <!-- Back to Top -->
    <a href="#" class="btn btn-primary back-to-top"
      ><i class="fa fa-angle-double-up"></i
    ></a>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="{{ url_for('static', filename='lib/easing/easing.min.js') }}"></script>

    <script src="{{ url_for('static', filename='lib/owlcarousel/dist/owl.carousel.min.js') }}"></script>

    <!-- Contact Javascript File -->
    <script src="{{ url_for('static', filename='mail/jqBootstrapValidation.min.js') }}"></script>
    <script src="{{ url_for('static', filename='mail/contact.js') }}"></script>

    <!-- Template Javascript -->
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
  </body>
</html>

app/templates/contact.html
{% extends "base.html" %}

{% block title %}Contact - EShopper{% endblock %}

{% block page_title %}Contact{% endblock %}

{% block breadcrumb %}Contact{% endblock %}

{% block content %}

<!-- Contact Start -->
<div class="container-fluid pt-5">
    <div class="text-center mb-4">
        <h2 class="section-title px-5"><span class="px-2">Contact For Any Queries</span></h2>
    </div>
    <div class="row px-xl-5">
        <div class="col-lg-7 mb-5">
            <div class="contact-form">

                <!-- Flash message block -->
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                                {{ message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}

                <!-- Contact Form -->
                <form method="POST" action="{{ url_for('routes_bp.contact') }}">
                    {{ form.hidden_tag() }} <!-- CSRF token hidden field -->

                    <div class="control-group">
                        {{ form.name.label(class="form-label") }}
                        {{ form.name(class="form-control", placeholder="Your Name") }}
                        {% if form.name.errors %}
                            <p class="help-block text-danger">{{ form.name.errors[0] }}</p>
                        {% endif %}
                    </div>

                    <div class="control-group">
                        {{ form.email.label(class="form-label") }}
                        {{ form.email(class="form-control", placeholder="Your Email") }}
                        {% if form.email.errors %}
                            <p class="help-block text-danger">{{ form.email.errors[0] }}</p>
                        {% endif %}
                    </div>

                    <div class="control-group">
                        {{ form.subject.label(class="form-label") }}
                        {{ form.subject(class="form-control", placeholder="Subject") }}
                        {% if form.subject.errors %}
                            <p class="help-block text-danger">{{ form.subject.errors[0] }}</p>
                        {% endif %}
                    </div>

                    <div class="control-group">
                        {{ form.message.label(class="form-label") }}
                        {{ form.message(class="form-control", placeholder="Message") }}
                        {% if form.message.errors %}
                            <p class="help-block text-danger">{{ form.message.errors[0] }}</p>
                        {% endif %}
                    </div>

                    <div>
                        {{ form.submit(class="btn btn-primary py-2 px-4") }}
                    </div>
                </form>
            </div>
        </div>
        <div class="col-lg-5 mb-5">
            <h5 class="font-weight-semi-bold mb-3">Get In Touch</h5>
            <p>Justo sed diam ut sed amet duo amet lorem amet stet sea ipsum, sed duo amet et. Est elitr dolor elitr erat sit sit. Dolor diam et erat clita ipsum justo sed.</p>
            <div class="d-flex flex-column mb-3">
                <h5 class="font-weight-semi-bold mb-3">Store 1</h5>
                <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street, New York, USA</p>
                <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
                <p class="mb-2"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
            </div>
            <div class="d-flex flex-column">
                <h5 class="font-weight-semi-bold mb-3">Store 2</h5>
                <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street, New York, USA</p>
                <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
                <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
            </div>
        </div>
    </div>
</div>
<!-- Contact End -->

{% endblock %}

app/templates/favorites.html
{% extends "base.html" %}

{% block title %}
    Favorites - EShopper
{% endblock %}

{% block page_title %}
    Favorite Products
{% endblock %}

{% block breadcrumb %}
    Favorites
{% endblock %}

{% block content %}

    <!-- Cart Start -->
    <div class="container-fluid pt-5">
        <div class="row px-xl-5 justify-content-center">
            <div class="col-lg-5 table-responsive mb-5">
                <table class="table table-bordered text-center mb-0">
                    <thead class="bg-secondary text-dark">
                        <tr>
                            <th>Products</th>
                            <th>Price</th>
                            <th>Remove</th>
                        </tr>
                    </thead>
                    <tbody class="align-middle">
                        {% for product in favorite_products %}
                            <tr>
                                <td class="align-middle">
                                    <img src="{{ url_for('static', filename=product.image) }}" alt="" style="width: 50px;"> {{ product.name }}
                                </td>
                                <td class="align-middle">${{ product.price }}</td>
                                <td class="align-middle">
                                    <form action="{{ url_for('routes_bp.remove_favorite', product_id=product.id) }}" method="POST">
                                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                                        <button class="btn btn-sm btn-primary" type="submit"><i class="fa fa-times"></i></button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>

                </table>
            </div>
        </div>
    </div>
    <!-- Cart End -->

    {% endblock %}
    

app/templates/login.html
{% extends "base.html" %}

{% block title %}Login - EShopper{% endblock %}

{% block page_title %}Login{% endblock %}

{% block breadcrumb %}Login{% endblock %}

{% block content %}

<!-- Contact Start -->
<div class="container-fluid pt-5">
    <div class="text-center mb-4">
        <h2 class="section-title px-5"><span class="px-2">Input Credentials For Login</span></h2>
    </div>
    <div class="row justify-content-center px-xl-5">
        <div class="col-lg-4 mb-5">
            <div class="contact-form">
                <div id="success"></div>
                <form  method="POST" action="{{ url_for('routes_bp.login') }}">

                    {{ form.hidden_tag() }}  <!-- This adds the CSRF token --> 
                    <div class="control-group">

                            <input type="email" class="form-control" id="email" name="email" placeholder="Your email" required />    

                        <p class="help-block text-danger"></p>
                    </div>
                    <div class="control-group">

                        <input type="password" class="form-control" id="password" name="password" placeholder="Your password" required />

                        <p class="help-block text-danger"></p>
                    </div>
                    <div class="d-flex justify-content-center">
                        <button class="btn btn-primary py-2 px-4" type="submit" id="sendMessageButton">Login</button>
                    </div>


                    
                </form>
            </div>
        </div>
    </div>
</div>
<!-- Contact End -->

{% endblock %}